### ISSUE TITLE
Is there a way to change back to the old board game backgrounds?

### ISSUE THREAD

**Issue by Medwynd** [EmilStenstrom/mybgg#27]
If an image was too small the background of a game used to be a blurred out version of the cover.  Is there a way to put this back in or turn it back on?  The current patchwork of randomly colored squares behind the titles seems like a big step backwards in viewing a collection.

**Comment by EmilStenstrom** [comment]
I’m sorry that you think this is a step backwards. I’m designated my mainly for myself here, so m just happy if what I do is useful for others.

As for the colors, they are taken from the album art, so as to match the covers. There are a couple of options on how to change them. Interested?

As for using the old stuff, I guess you could roll back to the old version, since everything is versioned here, but then you would not get any updates and new features...

**Comment by EmilStenstrom** [comment]
**For reference: Here's the old design:**

![mybgg-old-min](https://user-images.githubusercontent.com/224130/64073074-5cc52f80-cc99-11e9-88d9-3b1f836ed82f.png)

**And here's the new design:**

![mybgg-new-min](https://user-images.githubusercontent.com/224130/64073073-5cc52f80-cc99-11e9-96aa-8bd366e0e600.png)

**Comment by Medwynd** [comment]
Thanks, Ill take a look at it :)

**Comment by EmilStenstrom** [comment]
The color is set here: https://github.com/EmilStenstrom/mybgg/blob/master/app.js#L26 (as of 2019-09-01), and you can try changing "LightMuted" to any of the names below the images here: https://jariz.github.io/vibrant.js/
