### ISSUE TITLE
UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images

### ISSUE THREAD

**Issue by Medwynd** [EmilStenstrom/mybgg#34]
Ran into this issue when updating my collecton today.

E:\Python37-32\lib\site-packages\PIL\Image.py:932: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  "Palette images with Transparency expressed in bytes should be "

Rerunning with --debug.

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cf.geekdo-images.com:443
DEBUG:urllib3.connectionpool:https://cf.geekdo-images.com:443 "GET /thumb/img/Jcx2vf4RYzRyfhLS_usOe74hNpA=/fit-in/200x150/pic4309072.png HTTP/1.1" 200 7100
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'PLTE' 41 768
DEBUG:PIL.PngImagePlugin:STREAM b'tRNS' 821 256
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 1089 5995
E:\Python37-32\lib\site-packages\PIL\Image.py:932: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  "Palette images with Transparency expressed in bytes should be "

**Comment by EmilStenstrom** [comment]
Hi! I'm not sure this is an actual problem, since this is just a warning. If I open the image referred to above I get this: https://cf.geekdo-images.com/thumb/img/Jcx2vf4RYzRyfhLS_usOe74hNpA=/fit-in/200x150/pic4309072.png

So it seems Trickerion is the one triggering the warning. Do you see any problem with that game listing?

**Comment by EmilStenstrom** [comment]
This warning is now fixed in the latest version.
